### ISSUE TITLE
Unsatisfied input of me6211

### ISSUE THREAD

**Issue by jxltom** [openmv/openmv-boards#11]
From my understanding, the input of me6211 is 3.318v from PAM2305 and output should be 3.3v. But me6211 is LDO which usually requires dropout voltage larger than 0.1v. The input doesn't meet the criterial. Is this an issue?

**Comment by iabdalkader** [comment]
Hi, yes this is a known issue but I think we fixed it, at least on newer cams, and switched to 3.0v as far as I know @kwagyeman

**Comment by kwagyeman** [comment]
Yes

**Comment by jxltom** [comment]
So the fix is changing me6211 to 3.0v output? It looks like the base and plus board of v4 is still using 3.3v output as in https://github.com/openmv/openmv-boards/tree/master/openmv4/plus

**Comment by kwagyeman** [comment]
Actually... I think it's still a 3.3V output. It's always been. It's a design issue we didn't fix because it would have caused a schedule issue and it more or less already worked. On the later cameras like the OV5640 we put regulators onboard.

**Comment by jxltom** [comment]
Got it, thanks for the clarification. I would use the regulators on camera board instead.
